import React from "react";
import LearnMore from "../common/learnMore"
import Location from "../assets/images/location.png"
import Dream from "../assets/images/dream.png"
import Axel from "../assets/images/Axel.png"
import WeiMing from "../assets/images/WeiMing.png"
import "./meetTheCommunity.css"


export default () => {
  const commmunity = [{
    name: "Axel Del Castillo",
    body: "Axel grew up in Ecuador in a single parent family and, at the age of 18, moved alone from Ecuador to Canada to pursue a Bachelors degree in Materials Engineering at the University of Toronto. Initially, Axel was using a student loan from an Ecuador bank to support himself financially but this loan was cancelled after his first year of study, leaving him tens of thousands of dollars in debt and without financial support to continue his education. To support his studies, Axel’s single mother sold her retirement property while Axel took up a part time job at a local restaurant and took a loan from a family member. Axel also took up additional summer jobs and part time jobs related to his field of study (lab technician and materials testing technician) and was provided a grant from the university of Toronto, recognizing his commitment to his education and his talent for materials engineering. Axel dreams of launching a company that develops sustainable materials to decrease the pollution generated by raw materials extraction, industrial processing, and disposal as he has seen first hand the detrimental health effects mineral and petroleum extraction can have on the local population. He also hopes to branch into academia in the future to teach and inspire future generations of engineers to develop more sustainable practices and designs.",
    image: Axel,
    location: "Ecuador",
    dream: "To decrease pollution generated by the mining industry by developing sustainable materials",
  },
  {
    name: "Wei Ming Chen",
    body: "Wei Ming lives with his disabled parents in rural China. His father is visually handicapped and his mother became mentally disabled due to an accident. Wei Ming helps take care of the household while studying hard in school to pursue his dreams of becoming a doctor one day. Despite the challenges of balancing household work and school work, Wei Ming excels in his studies and shows exceptional talent in his biology course. With his talent for biology and his goal of becoming a doctor, Wei Ming dreams of giving back to the community in the future by helping the sick, disabled and elderly in their time of need. Wei Ming is especially inspired by the dedication and selflessness of frontline healthcare workers during the ongoing COVID pandemic and is resolved to contribute to society in the future with the same level of commitment. OWOC’s donations to Wei Ming will be used for the purchase of school supplies and related educational materials.",
    image: WeiMing,
    location: "China",
    dream: "To become a doctor dedicated to helping the sick and elderly"
  }]

  return(
    <div className={"community-container"}>
      <h1 className={"community-title"}>
        Meet The Community
      </h1>
      <div className={"initiatives-all"}>
        {
          commmunity.map((initiative) => <MeetTheCommunityCard {...initiative}/>)
        }
      </div>
      <LearnMore nextTitle={"Meet The Team"} nextDescription={"Work with us to provide a new level of transparency for a world of shared opportunity"} linkUri={"/meet-the-team"}/>
    </div>
  )
}

const MeetTheCommunityCard = ({ image, name, body, location, dream }) => (
  <div className={"community-card-container"}>
    <img src={image} className={"community-image"}/>
    <div className={"community-text-container"}>
      <h1 className={"community-name"}>
        { name }
      </h1>
      <p style={{fontSize: "0.9rem"}}>
        { body }
      </p>
    </div>
    <div>
      <div className={"community-icons-container"}>
        <div className={"community-location-container"}>
          <img src={Location} />
          <h3 style={{ margin: 0 }}>
            Location
          </h3>
          <p style={{ margin: 0, textAlign: "center", fontSize: "0.8rem" }}>
            {location}
          </p>
        </div>
        <div className={"community-location-container"}>
          <img src={Dream}/>
          <h3 style={{ margin: 0 }}>
            Dream
          </h3>
          <p style={{ margin: 0, textAlign: "center", fontSize: "0.8rem" }}>
            {dream}
          </p>
        </div>
      </div>
    </div>
  </div>
)
